;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014/6/23 15:43:08

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1002	1002	; 代码表 代码表.txt
#define IDH_1001	1001	; 首次登陆 首次登陆.txt
#define IDH_1047	1047	; 首次登陆安卓端接口 首次登陆安卓端接口.txt
#define IDH_1004	1004	; 注册页面_获取城市跟年级接口 注册页面_获取城市跟年级接口.txt
#define IDH_1005	1005	; 注册页面_家长注册接口 注册页面_家长注册接口.txt
#define IDH_1003	1003	; 注册页面_孩子注册接口 注册页面_孩子注册接口.txt
#define IDH_1006	1006	; 注册页面_学校注册申请 注册页面_学校注册申请.txt
#define IDH_1041	1041	; 找回密码接口 找回密码接口.txt
#define IDH_1046	1046	; 学校相册_批量上传接口 学校相册_批量上传接口.txt
#define IDH_1008	1008	; 宝宝去哪_五广告 宝宝去哪_五广告.txt
#define IDH_1017	1017	; 宝宝去哪里啦_获取经纬度及其下载url 宝宝去哪里啦_获取经纬度及其下载url.txt
#define IDH_1010	1010	; 我的_个人推送分页 我的_个人推送分页.txt
#define IDH_1011	1011	; 我的_家长修改信息接口 我的_家长修改信息接口.txt
#define IDH_1012	1012	; 我的_学生修改信息接口 我的_学生修改信息接口.txt
#define IDH_1015	1015	; 我的_修改页面获得信息接口 我的_修改页面获得信息接口.txt
#define IDH_1036	1036	; 我的_优惠分页列表接口 我的_优惠分页列表接口.txt
#define IDH_1037	1037	; 我的_报班下单或优惠详情接口 我的_报班下单或优惠详情接口.txt
#define IDH_1032	1032	; 选课报班添加城市条件 选课报班添加城市条件.txt
#define IDH_1034	1034	; 点击率人气_班（课程） 点击率人气_班（课程）.txt
#define IDH_1044	1044	; 退款接口 退款接口.txt
#define IDH_1040	1040	; 支付接口 支付接口.txt
#define IDH_1049	1049	; 支付接口1 支付接口1.txt
#define IDH_1033	1033	; 优惠专区详情接口 优惠专区详情接口.txt
#define IDH_1035	1035	; 优惠专区查询接口 优惠专区查询接口.txt
#define IDH_1043	1043	; 退款接口 退款接口.txt
#define IDH_1039	1039	; 支付接口 支付接口.txt
#define IDH_1048	1048	; 支付接口1 支付接口1.txt
#define IDH_1023	1023	; 找学校 找学校.txt
#define IDH_1025	1025	; 点击率人气_学校 点击率人气_学校.txt
#define IDH_1026	1026	; 点击率人气_学校相册 点击率人气_学校相册.txt
#define IDH_1024	1024	; 点击率人气_班（课程） 点击率人气_班（课程）.txt
#define IDH_1042	1042	; 地图学校是否显示及其显示颜色接口 地图学校是否显示及其显示颜色接口.txt
#define IDH_1045	1045	; 家长上传经纬度接口 家长上传经纬度接口.txt
#define IDH_1014	1014	; 我的_修改页面获得信息接口 我的_修改页面获得信息接口.txt
#define IDH_1016	1016	; 我的_校长修改信息接口 我的_校长修改信息接口.txt
#define IDH_1018	1018	; 我的_获取用户总校信息接口 我的_获取用户总校信息接口.txt
#define IDH_1019	1019	; 我的_修改总校信息接口 我的_修改总校信息接口.txt
#define IDH_1038	1038	; 我的_报班统计接口 我的_报班统计接口.txt
